[package]
name = "coverm"
version = "0.4.0"
authors = ["Ben Woodcroft <benjwoodcroft@gmail.com>"]
license = "GPL-3.0"
description = "Read coverage calculator for metagenomics"
homepage = "https://github.com/wwood/CoverM"
repository = "https://github.com/wwood/CoverM"
documentation = "https://github.com/wwood/CoverM"
readme = "README.md"
exclude = [ # Max upload is 10MB, as of writing test data was 15MB
  "tests/*",
]
default-run = "coverm"

[dependencies]
bio = "0.32.0"
rust-htslib = { version="0.32.*", default-features = false }
clap = "2.*"
log = "0.4.*"
env_logger = "0.7.*"
nix = "0.17.*"
tempdir = "0.3.*"
tempfile = "3.*"
ansi_term = "0.12"
lazy_static = "1.4.0"
rand = "0.7.*"
serde = "1.0"
version-compare = "0.0.10"
bird_tool_utils = {git = "https://github.com/wwood/bird_tool_utils", rev = "3b16f11ed421ae74c1a140f3894da02584bcb5b5"}
galah = {git = "https://github.com/wwood/galah", rev = "1408cf30d3a9403ff62a9b0a98be8701708a692a"}
man = {git = "https://github.com/wwood/man", rev = "6aed86ec55ab6c867b391658586a597770c6dcb1"}

[dev-dependencies]
assert_cli = "0.6.*"
# Run things before commit but not push
cargo-husky = { version="1", default-features = false, features=["precommit-hook", "run-cargo-test", "run-cargo-fmt"] }
